# VKontakte
SOCIAL_AUTH_VK_OAUTH2_KEY = '5380924'
SOCIAL_AUTH_VK_OAUTH2_SECRET = '4l9ZTBQG8WQ9HfEVwkHU'

# PayPal
PAYPAL_TEST = True
PAYPAL_WPP_USER = "feelemon-facilitator_api1.bk.ru"
PAYPAL_WPP_PASSWORD = "V8YVMYVAZ8BMBE5E"
PAYPAL_WPP_SIGNATURE = "AFcWxV21C7fd0v3bYYYRCpSSRl31AYbaxuiFJOhT5vr0ed.pfREU.Ekj"