# VKontakte
SOCIAL_AUTH_VK_OAUTH2_KEY = '5380924'
SOCIAL_AUTH_VK_OAUTH2_SECRET = '4l9ZTBQG8WQ9HfEVwkHU'

# PayPal
PAYPAL_TEST = True
PAYPAL_WPP_USER = ""
PAYPAL_WPP_PASSWORD = ""
PAYPAL_WPP_SIGNATURE = ""